#!/bin/bash

#this file is basically db-backup, but with an additional drop

source db-backup

if [[ "$BACKUP_COMPLETE" == "Complete" ]]; then
	$MYSQL_CMD -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASS -e "DROP DATABASE \`$db\`"
fi
